language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"

matrix:
  fast_finish: true

before_script:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb

services:
  - rethinkdb
